; PlatformIO Project Configuration File
; CosmicCYDScanner — COSMIC art portal + SD gallery + WiFi scanner overlay

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.f_cpu = 240000000L
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
lib_deps =
    moononournation/GFX Library for Arduino@1.4.7
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    bitbank2/JPEGDEC
